pip._internal.utils.logging._is_broken_pipe_error
506c2fea033e07c6f76f4d492955b22a