pip._internal.metadata.importlib._compat.BadMetadata.__init__
85269f04016fb0ae69b6970e23a513fd