pip._vendor.packaging.metadata.ExceptionGroup.__init__
5b1679c43a6ece5031b51b2dea66072c