pip._vendor.urllib3.util.retry.Retry._is_read_error
922ff036f7ec3570e6ab4f1c214abf6e