pip._internal.exceptions.UserInstallationInvalid.__str__
d2d2e4b9f3246cad713a1f2e2ffdd8b3