
+pip._vendor.urllib3.exceptions.RequestErrork
a/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/pip/_vendor/urllib3/exceptions.py# #("2*ù
2$ $(o
m
$ $(6-
+pip._vendor.urllib3.exceptions.RequestError"
url"__id*#

__unknown_file (

urlóð
% %(/
%2"type.__init__*)

__unknown_file (

	PoolError*K

__unknown_file (/-
+pip._vendor.urllib3.exceptions.RequestError*$

__unknown_file (

pool*'

__unknown_file (
	
message2__init__*
3*e
3
exceptions.py=;
' '(
%1"+pip._vendor.urllib3.exceptions.RequestError"
' '(

%1:
# #(
pool:
# #( 
url:
#" #()	
messageB/-
+pip._vendor.urllib3.exceptions.RequestErrorH