
Qpip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement.__str__
s/home/kali/Documentos/API-de-X/env/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/requirements.pyØ Ø("2*‘
2
Ù Ù(,‘
Ž

Ù Ù(
%1"__id*t

__unknown_file (X*VK
Ipip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirement"
_nameV
T

Ù Ù(,
%2"__concat*

Ù Ù(

%1* 

Ù Ù(+
 (unavailable)"

Ù Ù(,

%2BMK
Ipip._internal.resolution.resolvelib.requirements.UnsatisfiableRequirementH